name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - uses: actions/cache@v3
        with:
          ref: ${{ github.ref }}
          path: |
            ~/.cache/pip
            ~/.platformio/.cache  
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e mks_robin_lite_maple

      - name: Move firmware to base folder
        run: |
          cp .pio/build/mks_robin_lite_maple/mksLite.bin ./

      - name: Push firmware
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add mksLite.bin
          git commit -m "Compiled firmware"
          git push